image: geeksaccelerator/docker-library:golang1.12-docker

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""

before_script:
  - 'go install ./build/cicd'

stages:
  - build:dev
  - migrate:dev
  - deploy:dev
  - build:stage
  - migrate:stage
  - deploy:stage
  - build:prod
  - migrate:prod
  - deploy:prod

cache:
  key: ${CI_COMMIT_REF_SLUG}

# Everything should get this, whether through subtemplates or explicitly
# embedded in a job.
.job_tmpl: &job_tmpl
  only:
    - master

.build_tmpl: &build_tmpl
  <<: *job_tmpl
  script:
    - 'cicd --env=${TARGET_ENV} build ${TARGET_TYPE} --name=${TARGET_REF}'

.deploy_tmpl: &deploy_tmpl
  <<: *job_tmpl
  script:
    - 'cicd --env=${TARGET_ENV} deploy ${TARGET_TYPE} --name=${TARGET_REF}'

.migrate_tmpl: &migrate_tmpl
  <<: *job_tmpl
  script:
    - 'cicd --env=${TARGET_ENV} schema migrate'

db:migrate:prod:
  <<: *migrate_tmpl
  stage: migrate:prod
  tags:
    - prod
  only:
    - master
    - prod
    - /^prod-.*$/
  variables:
    TARGET_ENV: 'prod'
    AWS_USE_ROLE: 'true'

webapp:build:prod:
  <<: *build_tmpl
  stage: build:prod
  tags:
    - prod
  only:
    - master
    - prod
    - prod-web-app
  variables:
    TARGET_ENV: 'prod'
    TARGET_TYPE: 'service'
    TARGET_REF: 'web-app'
    AWS_USE_ROLE: 'true'
webapp:deploy:prod:
  <<: *deploy_tmpl
  stage: deploy:prod
  tags:
    - prod
  only:
    - master
    - prod
    - prod-web-app
  dependencies:
    - 'webapp:build:prod'
    - 'db:migrate:prod'
  variables:
    TARGET_ENV: 'prod'
    TARGET_TYPE: 'service'
    TARGET_REF: 'web-app'
    AWS_USE_ROLE: 'true'

webapi:build:prod:
  <<: *build_tmpl
  stage: build:prod
  tags:
    - prod
  only:
    - master
    - prod
    - prod-web-api
  variables:
    TARGET_ENV: 'prod'
    TARGET_TYPE: 'service'
    TARGET_REF: 'web-api'
    AWS_USE_ROLE: 'true'
webapi:deploy:prod:
  <<: *deploy_tmpl
  stage: deploy:prod
  tags:
    - prod
  only:
    - master
    - prod
    - prod-web-api
  dependencies:
    - 'webapi:build:prod'
    - 'db:migrate:prod'
  variables:
    TARGET_ENV: 'prod'
    TARGET_TYPE: 'service'
    TARGET_REF: 'web-api'
    AWS_USE_ROLE: 'true'

ddlogscollector:build:prod:
  <<: *build_tmpl
  stage: build:prod
  tags:
    - prod
  only:
    - master
    - prod
    - prod-ddlogs
  variables:
    TARGET_ENV: 'prod'
    TARGET_TYPE: 'function'
    TARGET_REF: 'ddlogscollector'
    AWS_USE_ROLE: 'true'
ddlogscollector:deploy:prod:
  <<: *deploy_tmpl
  stage: deploy:prod
  tags:
    - prod
  only:
    - master
    - prod
    - prod-ddlogs
  dependencies:
    - 'ddlogscollector:build:prod'
    - 'db:migrate:prod'
  variables:
    TARGET_ENV: 'prod'
    TARGET_TYPE: 'function'
    TARGET_REF: 'ddlogscollector'
    AWS_USE_ROLE: 'true'

